def text
  "By
  Erin Smith,
  writer at

  Creators.co

  In the realm of #superheroes, everyone has their favorite side. #Marvel or #DC. Each universe has its amazing array of heroes, and villains. Everyone thinks their side is the best.What makes this whole 'Marvel vs DC' war so much fun? It leads to good old fashion debates over who would beat who!See also:Today, I have decided to pit DC's #Robin/#Nightwing against Marvel's #WinterSoldier. Both are sidekicks to pretty awesome heroes, #Batman and #CaptainAmerica, but which mentor has helped their sidekick the best?They both started out small. #BuckyBarnes was just a regular soldier, and #DickGrayson was our famous Boy Wonder. They worked with our great heroes and learned their 'trade'. Eventually, they would branch out on their own, becoming Marvel's Winter Soldier and DC's Nightwing.So, let's get down to business. If these two fought, who would win? Grayson or Barnes?To figure this out, we have to take a closer look at the two heroes.

  BUCKY BARNES: ONCE THE SOLDIER, NOW THE DEADLY ASSASSIN.

  First, let's get some background. How did Buchanan Barnes become the Winter Soldier? When we first meet him in the comics, and in the #MCU, Bucky is just a normal soldier. He follows Captain America on his missions, and later is believed to die at the hands of the Nazis in World War II. Cap goes down to take his icy nap, and the one armed Bucky gets found by a Soviet submarine. This is the birth of the Winter Soldier. They brainwash him and supply him with a bionic arm. Taking his already toned skills as a soldier, they enhance him and create the assassin we know today.During Marvel's newest installment, Captain America: Civil War, Bucky shows off more of his skills. We got to see quite a bit of what he can do in Captain America: The Winter Soldier, but we get to see more of his skills used against different people, and items, in the newer movie. His skill-sets includes:The Winter Soldier is a formidable foe. You want him on your side. However, he does have a couple of weaknesses that can be used against him.'Longing. Rusted. Seventeen. Daybreak. Furnace. Nine. Benign. Homecoming. One. Freight Car.'During his time in #HYDRA, Buchanan Barnes' mind got wiped and programmed to follow horrible orders. To send his programmed brain into a restart, making him easier to control and handle, this series of words would be said to him:Longing. Rusted. Seventeen. Daybreak. Furnace. Nine. Benign. Homecoming. One. Freight Car...soldier? - Baron Zemo, Captain America: Civil War (2016) As shown in Captain America: Civil War, this still works on his mind, despite his wanting to be Bucky Barnes again. Anyone who has these words can take him over and control him. Knowing that his mind is so weak, and his past haunting him, threatens the Winter Soldier everyday. This is his greatness weakness, and that is why Bucky and Steve Rogers seek T'Challa's advice.He is weak against little spandex wearing teenagers. The look of disbelief and confusion on Bucky's face is my favorite part of this whole scene! As far as we know, this Spider-Man only has the normal spidey abilities: jumping, climbing, and super strength. Apparently, Parker's super strength is better than Bucky's metal arm. It's possible that he is not as powerful against super strength as we may have thought.So what about Nightwing?

  DICK GRAYSON: PROTEGE TO MASTER

  Like Barnes, Dick Grayson starts off small. First seen beside our lovable Batman in 1940, he became our first Robin. But how did he go from the Boy Wonder to Nightwing?Well, like Batman, he has a traumatic backstory.He was part of the #FlyingGraysons. They were comprised of Dick and his parents. Due to some misunderstandings in the circus, his parents were murdered which left the young boy to fend for his own. This is how Bruce Wayne, the Batman, found him. He took young Grayson under his wing, and they would eventually create the ultimate duo: Batman and Robin.Under Batman, he learned how to use his acrobat skills to fight for justice. He grew under his mentor's leadership until deciding to break off on his own. This is where Nightwing is born. Dick Grayson, now Nightwing, becomes his own vigilante. In the comics, we can follow him as he helps lead the young #TeenTitans and defeat villains such as Tony Zucco and Trigon, two of Nightwing's major foes. He is also the leader in the TV show, #YoungJustice.Now, when it comes to his skill-sets, Nightwing lacks almost nothing.With this array of expertise, you also have to throw in there that he has been trained by the one and only Batman. With that in mind, it's hard to actually find weaknesses in Nightwing that he wouldn't be able to overcome in some way, shape, or form. One major weakness, that is not easily remedied, is super strength. Without someone like Superboy nearby, Nightwing is unable to lift heavy objects and wouldn't do well in a good ol' fashion fist fight with someone like General Zod.

  IN ACTION

  One final thing before I let you make your decision, a couple of my favorite fight scenes including The Winter Soldier or Nightwing. This is a great way to see them both in action, and how they handle different situations.This scene is from #CaptainAmericaCivilWar, and is one of my favorites. This is simply because we get to see Bucky take out several of the Avengers, and Black Panther. It is intriguing, and it also gives us insight into how he fares against each type of fighting style: the assassin, the super soldier, and the tech guy.Now we have Nightwing, the Young Justice version. I love this TV show, and Robin/Nightwing is my favorite character in the show. We get to see him working on his own, and also with his teammates to defeat Black Manta and his minions. It gives us examples of his different abilities.Sorry, no super-powers for your collar to turn off.Nothing to manipulate like someone's metal arm.

  NOW DECIDE.

  So, there you have it. Dick Grayson and Bucky Barnes.They are both incredible, and it is really hard for me to decide which would actually win in a fight.Biased opinion? Bucky all the way, but if I'm honest, Nightwing could possibly have the upper hand in more situations than the Winter Soldier could. I personally think it would depend on the situation. If either was being stealthy and hunting the other, they would have the upper hand.But what do you think?Sources: Youtube, IMDb"
end
